<?php
// $Id$

/**
 * @file
 * Add phone number fields to Location address.
 */

/**
 * Implementation of hook_locationapi().
 */
function location_phone_locationapi(&$location, $op) {
  switch ($op) {
    case 'fields':
      return array('phone' => t('Phone number'));

    case 'collection default':
      return array('phone' => 0);

    case 'save':
      db_query('DELETE FROM {location_phone} WHERE lid = %d', $location['lid']);
      if (!empty($location['phone'])) {
        db_query("INSERT INTO {location_phone} (lid, phone) VALUES (%d, '%s')", $location['lid'], $location['phone']);
      }
      break;
    case 'load':
      if ($row = db_fetch_object(db_query('SELECT phone FROM {location_phone} WHERE lid = %d', $location['lid']))) {
        return (array) $row;
      }

      break;
    case 'delete':
      db_query('DELETE FROM {location_phone} WHERE lid = %d', $location['lid']);
      break;
  }
}
