<?php
// $Id$

// Uzbekistan

function location_province_list_uz() {
  return array('AN' => "Andijon",
    'BU' => "Buxoro",
    'FA' => "Farg'ona",
    'JI' => "Jizzax",
    'NG' => "Namangan",
    'NW' => "Navoiy",
    'QA' => "Qashqadaryo",
    'QR' => "Qoraqalpog'iston Republikasi",
    'SA' => "Samarqand",
    'SI' => "Sirdaryo",
    'SU' => "Surxondaryo",
    'TK' => "Toshkent city",
    'TO' => "Toshkent region",
    'XO' => "Xorazm");
}

?>