<?php

// Guyana

function location_province_list_gy() {
  return array('BW' => "Barima-Waini",
    'CM' => "Cuyuni-Mazaruni",
    'DM' => "Demerara-Mahaica",
    'EC' => "East Berbice-Corentyne",
    'EW' => "Essequibo Islands-West Demerara",
    'MB' => "Mahaica-Berbice",
    'PM' => "Pomeroon-Supenaam",
    'PI' => "Potaro-Siparuni",
    'UD' => "Upper Demerara-Berbice",
    'UT' => "Upper Takutu-Upper Essequibo");
}

?>