<?php

// Switzerland

function location_province_list_ch() {
  return array('ZH' => "Zurich",
    'BE' => "Bern",
    'LU' => "Lucerne",
    'UR' => "Uri",
    'SZ' => "Schwyz",
    'OW' => "Obwalden",
    'NW' => "Nidwalden",
    'GL' => "Glarus",
    'ZG' => "Zug",
    'FR' => "Fribourg",
    'SO' => "Solothurn",
    'BS' => "Basel-Stadt",
    'BL' => "Basel-Landschaft",
    'SH' => "Schaffhausen",
    'AR' => "Appenzell Ausserrhoden",
    'AI' => "Appenzell Innerhoden",
    'SG' => "St. Gallen",
    'GR' => "Graubunden",
    'AG' => "Aargau",
    'TG' => "Thurgau",
    'TI' => "Ticino",
    'VD' => "Vaud",
    'VS' => "Valais",
    'NE' => "Neuchâtel",
    'GE' => "Geneva",
    'JU' => "Jura");
}

?>