<?php

// Uruguay

function location_province_list_uy() {
  return array('AR' => "Artigas",
    'CA' => "Canelones",
    'CL' => "Cerro Largo",
    'CO' => "Colonia",
    'DU' => "Durazno",
    'FS' => "Flores",
    'FA' => "Florida",
    'LA' => "Lavalleja",
    'MA' => "Maldonado",
    'MO' => "Montevideo",
    'PA' => "Paysandu",
    'RN' => "Rio Negro",
    'RV' => "Rivera",
    'RO' => "Rocha",
    'SL' => "Salto",
    'SO' => "Soriano",
    'SJ' => "San Jose",
    'TT' => "Treinta y Tres");
}

?>