<?php
// $Id$

// Somalia

function location_province_list_so() {
  return array('AW' => "Awdal",
    'BK' => "Bakool",
    'BN' => "Banaadir",
    'BR' => "Bari",
    'BY' => "Bay",
    'GA' => "Galguduud",
    'GE' => "Gedo",
    'HI' => "Hiiraan",
    'JD' => "Jubbada Dhexe",
    'JH' => "Jubbada Hoose",
    'MU' => "Mudug",
    'NU' => "Nugaal",
    'SA' => "Sanaag",
    'SD' => "Shabeellaha Dhexe",
    'SH' => "Shabeellaha Hoose",
    'SL' => "Sool",
    'TO' => "Togdheer",
    'WG' => "Woqooyi Galbeed");
}

?>