<?php
// $Id$

// Kiribati

function location_province_list_ki() {
  return array('AG' => "Abaiang",
    'AM' => "Abemama",
    'AK' => "Aranuka",
    'AO' => "Arorae",
    'BA' => "Banaba",
    'BE' => "Beru",
    'bT' => "Butaritari",
    'KA' => "Kanton",
    'KR' => "Kiritimati",
    'KU' => "Kuria",
    'MI' => "Maiana",
    'MN' => "Makin",
    'ME' => "Marakei",
    'NI' => "Nikunau",
    'NO' => "Nonouti",
    'ON' => "Onotoa",
    'TT' => "Tabiteuea",
    'TR' => "Tabuaeran",
    'TM' => "Tamana",
    'TW' => "Tarawa",
    'TE' => "Teraina");
}

?>