<?php

// Denmark

function location_province_list_dk() {
  return array('CC' => "Copenhagen (municipality)",
    'FC' => "Frederiksberg (municipality)",
    'CO' => "Copenhagen",
    'FR' => "Frederiksborg",
    'RO' => "Roskilde",
    'WZ' => "West Zealand",
    'ST' => "Storstrom",
    'FU' => "Funen",
    'SJ' => "South Jutland",
    'RB' => "Ribe",
    'VK' => "Vejle",
    'RK' => "Ringkjobing",
    'VB' => "Viborg",
    'NJ' => "North Jutland",
    'AR' => "Arhus",
    'BH' => "Bornholm",
    'GL' => "Greenland",
    'FO' => "Faroe Islands");
}

?>